[package]
name = "update-jekyll-content-to-gatsby"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quicli = "0.4"
structopt = "0.2"
regex = "1"
lazy_static = "1.4.0"